FROM golang:1.24-alpine

RUN apk add --no-cache upx

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080
ENV PORT=8080

RUN GOOS=linux go build -o main .

ENTRYPOINT [ "./main" ]